version: '3'

services:
  freshrss:
    image: freshrss/freshrss:latest
    ports:
      - "8080:80"
    volumes:
      - ./freshrss:/var/www/FreshRSS/data
    restart: always

  fulltextrss:
    image: fivefilters/full-text-rss:latest
    ports:
      - "8090:80"
    volumes:
      - ./fulltextrss:/var/www/html/cache
    restart: always

  kalilinux:
    image: kalilinux/kali-rolling
    stdin_open: true
    tty: true
    volumes:
      - kali-data:/mnt/data
    restart: always

  ubuntu:
    image: ubuntu:latest
    volumes:
      - ubuntu-data:/mnt/data
    restart: always

volumes:
  kali-data:
  ubuntu-data:
  freshrss-data:
  fulltextrss-data:
